// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrEaVG-BXIVE2tQMcvxZMTWe4a45MUtqI',
    appId: '1:715274502588:android:b4551700e9469f84836bb9',
    messagingSenderId: '715274502588',
    projectId: 'rea-1-556fd',
    storageBucket: 'rea-1-556fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQJfpRTXxvUPw3cZFg2QrN9uH-93vuHmY',
    appId: '1:715274502588:ios:95512324e9c129f7836bb9',
    messagingSenderId: '715274502588',
    projectId: 'rea-1-556fd',
    storageBucket: 'rea-1-556fd.firebasestorage.app',
    iosBundleId: 'net.tadel.reaprime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQJfpRTXxvUPw3cZFg2QrN9uH-93vuHmY',
    appId: '1:715274502588:ios:95512324e9c129f7836bb9',
    messagingSenderId: '715274502588',
    projectId: 'rea-1-556fd',
    storageBucket: 'rea-1-556fd.firebasestorage.app',
    iosBundleId: 'net.tadel.reaprime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRcsPBkdEjX9dEDwb5Sgy6BRAzR9rT1wU',
    appId: '1:715274502588:web:49d854d0d662f929836bb9',
    messagingSenderId: '715274502588',
    projectId: 'rea-1-556fd',
    authDomain: 'rea-1-556fd.firebaseapp.com',
    storageBucket: 'rea-1-556fd.firebasestorage.app',
    measurementId: 'G-F7G4P66VF4',
  );

}